# Generated by Django 4.0.6 on 2022-07-30 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=100)),
                ('lastname', models.CharField(default='', max_length=100)),
                ('username', models.CharField(default='', max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(default='', max_length=255)),
                ('userType', models.CharField(default='', max_length=1)),
                ('isLock', models.CharField(default='', max_length=1)),
                ('isverified', models.CharField(default='', max_length=1)),
                ('imgURL', models.CharField(default='', max_length=255)),
                ('role', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
