# Generated by Django 4.0.6 on 2022-08-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountVerification_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_email', models.EmailField(max_length=254)),
                ('verification_code', models.CharField(default='', max_length=255)),
                ('verified', models.CharField(default='', max_length=1)),
                ('user_type', models.CharField(default='', max_length=100)),
                ('sent_count', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=100)),
                ('lastname', models.CharField(default='', max_length=100)),
                ('contactnumber', models.BigIntegerField()),
                ('address', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(default='', max_length=255)),
                ('userType', models.CharField(default='', max_length=1)),
                ('isLock', models.CharField(default='', max_length=1)),
                ('isverified', models.CharField(default='', max_length=1)),
                ('imgURL', models.CharField(default='', max_length=255)),
                ('sec_question', models.CharField(default='', max_length=150)),
                ('sec_answer', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(default='', max_length=155)),
                ('projectdetails', models.CharField(default='', max_length=255)),
                ('projectcategory', models.CharField(default='', max_length=100)),
                ('projecttype', models.CharField(default='', max_length=100)),
                ('projectfeatures', models.CharField(default='', max_length=255)),
                ('projectprice', models.BigIntegerField()),
                ('clientEmail', models.CharField(default='', max_length=255)),
                ('projectstatus', models.CharField(default='', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
