# Generated by Django 4.0.6 on 2022-08-08 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restful_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessowner',
            name='sec_answer',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='businessowner',
            name='sec_question',
            field=models.CharField(default='', max_length=150),
        ),
    ]
