# Generated by Django 4.0.6 on 2022-08-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restful_api', '0002_accountverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountVerification_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_email', models.EmailField(max_length=254)),
                ('verification_code', models.CharField(default='', max_length=255)),
                ('verified', models.CharField(default='', max_length=1)),
                ('user_type', models.CharField(default='', max_length=100)),
                ('sent_count', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AccountVerification',
        ),
    ]
