# Generated by Django 4.0.6 on 2022-08-16 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restful_api', '0005_tokenization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=100)),
                ('lastname', models.CharField(default='', max_length=100)),
                ('contactnumber', models.BigIntegerField()),
                ('address', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(default='', max_length=255)),
                ('userType', models.CharField(default='', max_length=1)),
                ('isLock', models.CharField(default='', max_length=1)),
                ('isverified', models.CharField(default='', max_length=1)),
                ('imgURL', models.CharField(default='', max_length=255)),
                ('sec_question', models.CharField(default='', max_length=150)),
                ('sec_answer', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(default='', max_length=100)),
                ('purpose', models.CharField(default='', max_length=100)),
                ('birthdate', models.DateField()),
                ('studylevel', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_email', models.EmailField(max_length=254)),
                ('req_studentIdFileURL', models.CharField(default='', max_length=255)),
                ('req_studentBirthCertURL', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
