# Generated by Django 4.1 on 2022-08-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restful_api', '0007_administrator'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(default='', max_length=150)),
                ('message', models.TextField()),
            ],
        ),
    ]
