# Generated by Django 4.1.1 on 2022-10-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restful_api', '0008_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(default='', max_length=100)),
                ('isActive', models.CharField(default='', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodCategoryFKId', models.BigIntegerField()),
                ('prodScaleFKId', models.BigIntegerField()),
                ('productFeatureName', models.CharField(default='', max_length=100)),
                ('isActive', models.CharField(default='', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductProjectScales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectScale', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(default='', max_length=255)),
                ('productCategory', models.CharField(default='', max_length=100)),
                ('productPrice', models.BigIntegerField()),
                ('productScale', models.CharField(default='', max_length=100)),
                ('productDescription', models.CharField(default='', max_length=255)),
                ('productTechStack', models.CharField(default='', max_length=100)),
                ('productImageURL', models.CharField(default='', max_length=255)),
                ('productFeatures', models.CharField(default='', max_length=255)),
                ('isActive', models.CharField(default='', max_length=1)),
                ('createdBy', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTechnologies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
