# Generated by Django 4.1.1 on 2022-10-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restful_api', '0009_productcategories_productfeatures_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingManagement_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainingTitle', models.CharField(default='', max_length=100)),
                ('trainingCategory', models.CharField(default='', max_length=100)),
                ('trainingDescription', models.CharField(default='', max_length=255)),
                ('trainingDays', models.CharField(default='', max_length=100)),
                ('trainingImgURL', models.CharField(default='', max_length=255)),
                ('trainingStatus', models.CharField(default='', max_length=255)),
                ('trainingLevel', models.CharField(default='', max_length=255)),
                ('trainingProctor', models.CharField(default='', max_length=100)),
                ('trainingCapacity', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
